name: update

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up env variables from secrets
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "NEWSAPI_KEY=${{ secrets.NEWSAPI_KEY }}" >> $GITHUB_ENV
      
      - name: Render README.md
        run: |
          python3 render.py
      
      - name: Deploy
        run: |
          git config user.name "p-rivero README generator"
          git config user.email "no@email.here"
          git add .
          git commit -am "Update dynamic content"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
